apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: mike
spec:
  clusterIP: 10.108.118.1
  clusterIPs:
    - 10.108.118.1
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32421
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: myapp
  sessionAffinity: None
  type: LoadBalancer
